# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='instruments',
            name='players',
        ),
        migrations.AlterField(
            model_name='member',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Instrument'),
        ),
        migrations.DeleteModel(
            name='Instruments',
        ),
    ]
