FROM python:3.5

ENV PYTHONUNBUFFERED 1

WORKDIR /jatumba-backend
COPY Pipfile* ./
RUN pip install pipenv && \
    pipenv install && \
    pipenv install gunicorn

COPY . /jatumba-backend
RUN mkdir -p /var/log/daphne

CMD /root/.local/share/virtualenvs/jatumba-backend/bin/gunicorn \
    TPD.wsgi:application \
    --bind=:8000 \
    --access-logfile /var/log/gunicorn/access.log \
    --error-logfile /var/log/gunicorn/error.log \
    --log-level debug
