FROM bkhasanov/jatumba-backend-base
MAINTAINER Bulat Khasanov <afti@yandex.ru>

RUN pip install daphne && \
    mkdir -p /var/log/daphne

CMD daphne TPD.asgi:channel_layer \
    --bind 0.0.0.0 \
    --port 9000 \
    --access-log /var/log/daphne/access.log \
    --verbosity 2
