FROM bkhasanov/jatumba-backend-base

RUN pipenv install gunicorn && \
    mkdir -p /var/log/gunicorn

CMD /root/.local/share/virtualenvs/jatumba-backend/bin/gunicorn \
    TPD.wsgi:application \
    --bind=:8000 \
    --access-logfile /var/log/gunicorn/access.log \
    --error-logfile /var/log/gunicorn/error.log \
    --log-level debug
