FROM bkhasanov/jatumba-backend-base
MAINTAINER Bulat Khasanov <afti@yandex.ru>

RUN pipenv install gunicorn && \
    mkdir -p /var/log/gunicorn

CMD $PYTHON_BIN_PATH/python \
    manage.py \
    collectstatic \
    --noinput \
    && \
    ${PYTHON_BIN_PATH}/gunicorn \
    TPD.wsgi:application \
    --bind=:8000 \
    --access-logfile /var/log/gunicorn/access.log \
    --error-logfile /var/log/gunicorn/error.log \
    --log-level debug
