FROM python:3.6
MAINTAINER Bulat Khasanov <afti@yandex.ru>

ENV PYTHONUNBUFFERED=1 \
    STATIC_ROOT=/static \
    MEDIA_ROOT=/media

WORKDIR /jatumba-backend
COPY Pipfile* ./
RUN pip install pipenv && \
    pipenv install --system

COPY . .
