# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.TextField()),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Composition')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Instrument')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='access_token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
