# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 07:55
from __future__ import unicode_literals

from django.db import migrations

from api.permissions import renovate_permissions


def forwards_func(apps, schema_editor):
    renovate_permissions()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
