# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 20:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160417_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratetracksnapshot',
            name='diff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaborate_snapshot', to='api.CollaborateTrackDiff'),
        ),
    ]
