# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160326_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackhistory',
            name='modified_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tracks_modified', to=settings.AUTH_USER_MODEL, verbose_name='Автор изменения'),
            preserve_default=False,
        ),
    ]
