# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 07:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160417_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='api.Composition', verbose_name='Композиция')),
            ],
            options={
                'verbose_name': 'Версия композиции',
                'verbose_name_plural': 'Версии композиций',
            },
        ),
        migrations.RemoveField(
            model_name='collaboratetrackdiff',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='collaboratetracksnapshot',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='collaboratetracksnapshot',
            name='diff',
        ),
        migrations.RemoveField(
            model_name='collaboratetracksnapshot',
            name='track',
        ),
        migrations.RemoveField(
            model_name='compositionbranch',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='trackdiff',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='trackdiff',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='trackdiff',
            name='track',
        ),
        migrations.RemoveField(
            model_name='tracksnapshot',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='tracksnapshot',
            name='track',
        ),
        migrations.RemoveField(
            model_name='track',
            name='composition',
        ),
        migrations.AddField(
            model_name='track',
            name='entity',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Сущность'),
        ),
        migrations.DeleteModel(
            name='CollaborateTrackDiff',
        ),
        migrations.DeleteModel(
            name='CollaborateTrackSnapshot',
        ),
        migrations.DeleteModel(
            name='CompositionBranch',
        ),
        migrations.DeleteModel(
            name='TrackDiff',
        ),
        migrations.DeleteModel(
            name='TrackSnapshot',
        ),
        migrations.AddField(
            model_name='track',
            name='composition_version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.CompositionVersion', verbose_name='Композиция'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='compositionversion',
            index_together=set([('composition', 'id')]),
        ),
    ]
