# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160422_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('composition_version', 'order'), 'verbose_name': 'Дорожка', 'verbose_name_plural': 'Дорожки'},
        ),
        migrations.AddField(
            model_name='track',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('composition_version', 'order')]),
        ),
    ]
