# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sessions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Session',
        ),
    ]
