# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public_username',
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_profile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_profile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
