# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20160424_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Band', verbose_name='Музыкальная группа')),
            ],
            options={
                'ordering': ('-datetime',),
                'verbose_name_plural': 'Сообщения',
                'verbose_name': 'Сообщение',
            },
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together=set([('band', 'datetime')]),
        ),
    ]
