# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160228_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fb_profile',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_profile',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
