# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160502_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='api.Composition', verbose_name='Композиция')),
                ('composition_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='api.CompositionVersion', verbose_name='Версия композиции')),
            ],
            options={
                'verbose_name_plural': 'Форки',
                'verbose_name': 'Форк',
            },
        ),
    ]
