# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 00:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_fork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fork',
            name='composition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fork', to='api.Composition', verbose_name='Композиция'),
        ),
    ]
