# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160503_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='instrument',
        ),
        migrations.AddField(
            model_name='instrument',
            name='users',
            field=models.ManyToManyField(related_name='instruments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
