# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 02:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160504_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionversion',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 5, 2, 29, 55, 357870, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
