# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_compositionversion_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compositionversion',
            old_name='datetime',
            new_name='create_datetime',
        ),
    ]
