# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20160505_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionversion',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='composition_versions', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compositionversion',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_versions', to='api.Composition', verbose_name='Композиция'),
        ),
    ]
