# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160509_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionversion',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.Composition', verbose_name='Композиция'),
        ),
    ]
