# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 11:53
from __future__ import unicode_literals

from django.db import migrations, models

import api.models.auth


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20160509_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.auth.avatar_upload_to),
        ),
    ]
