# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 13:25
from __future__ import unicode_literals

import api.models.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.auth.avatar_upload_to, verbose_name='Аватар'),
        ),
    ]
