# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 08:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20160510_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fork',
            old_name='composition',
            new_name='destination_composition',
        ),
        migrations.RenameField(
            model_name='fork',
            old_name='composition_version',
            new_name='source_composition_version',
        ),
        migrations.AddField(
            model_name='fork',
            name='source_composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='api.Composition', verbose_name='Композиция, которую форкнули'),
        ),
    ]
