# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 08:22
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Fork = apps.get_model('api', 'Fork')
    for fork in Fork.objects.select_related('source_composition_version'):
        fork.source_composition = fork.source_composition_version.composition
        fork.save(update_fields=('source_composition',))


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0022_auto_20160522_0821'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
