# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 08:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_fullfil_fork_source_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fork',
            name='destination_composition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_destination_fork', to='api.Composition', verbose_name='Новая композиция'),
        ),
        migrations.AlterField(
            model_name='fork',
            name='source_composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_source_forks', to='api.Composition', verbose_name='Композиция, которую форкнули'),
        ),
    ]
