# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20160522_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compositionversion',
            options={'ordering': ('create_datetime',), 'verbose_name': 'Версия композиции', 'verbose_name_plural': 'Версии композиций'},
        ),
    ]
