# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160523_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='difftrack',
            old_name='entity',
            new_name='entity_old',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='entity',
            new_name='entity_old',
        ),
    ]
