# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 11:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160523_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difftrack',
            name='entity',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Сущность'),
        ),
        migrations.AlterField(
            model_name='track',
            name='entity',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Сущность'),
        ),
    ]
