# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 00:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20160612_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCompositionVersionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Composition', verbose_name='Композиция')),
                ('composition_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.CompositionVersion', verbose_name='Версия композиции')),
            ],
            options={
                'verbose_name_plural': 'Связи между последними версиями композиций и композициями',
                'verbose_name': 'Связь между последней версией композиции и композицией',
            },
        ),
    ]
