# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 23:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20160611_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='difftrack',
            name='entity',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Id звука'), size=32, verbose_name='Сектор'), null=True, size=None, verbose_name='Сущность'),
        ),
        migrations.AddField(
            model_name='track',
            name='entity',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Id звука'), size=32, verbose_name='Сектор'), null=True, size=None, verbose_name='Сущность'),
        ),
    ]
