# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 23:49
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Track = apps.get_model('api', 'Track')
    for track in Track.objects.all():
        track.entity = track.entity_old
        track.save()

    DiffTrack = apps.get_model('api', 'DiffTrack')
    for diff_track in DiffTrack.objects.all():
        diff_track.entity = diff_track.entity_old
        diff_track.save()


def backward(apps, schema_editor):
    Track = apps.get_model('api', 'Track')
    for track in Track.objects.all():
        track.entity_old = track.entity
        track.save()

    DiffTrack = apps.get_model('api', 'DiffTrack')
    for diff_track in DiffTrack.objects.all():
        diff_track.entity_old = diff_track.entity
        diff_track.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0028_auto_20160611_2347'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
