# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 00:38
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    LastCompositionVersionLink = apps.get_model('api', 'LastCompositionVersionLink')
    Composition = apps.get_model('api', 'Composition')
    CompositionVersion = apps.get_model('api', 'CompositionVersion')
    for composition in Composition.objects.all():
        composition_version = composition.versions.last()
        if composition_version is None:
            composition_version = CompositionVersion.objects.create(
                composition=composition,
                author=composition.band.leader.member.user
            )
        LastCompositionVersionLink.objects.update_or_create(
            composition=composition,
            defaults={'composition_version': composition_version}
        )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0028_lastcompositionversionlink'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
