# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 01:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_fill_last_composition_version_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastcompositionversionlink',
            name='composition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_composition_version_link', to='api.Composition', verbose_name='Композиция'),
        ),
        migrations.AlterField(
            model_name='lastcompositionversionlink',
            name='composition_version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_composition_version_link', to='api.CompositionVersion', verbose_name='Версия композиции'),
        ),
    ]
