# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 23:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_pass_data_to_new_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difftrack',
            name='entity_old',
        ),
        migrations.RemoveField(
            model_name='track',
            name='entity_old',
        ),
        migrations.AlterField(
            model_name='difftrack',
            name='entity',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Id звука'), size=32, verbose_name='Сектор'), size=None, verbose_name='Сущность'),
        ),
        migrations.AlterField(
            model_name='track',
            name='entity',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, verbose_name='Id звука'), size=32, verbose_name='Сектор'), size=None, verbose_name='Сущность'),
        ),
    ]
