FROM nginx:alpine

ADD https://github.com/YetAnotherTeam/jatumba-frontend /root/jatumba-frontend
#RUN rm /etc/nginx/conf.d/default.conf
#COPY conf.d/nginx /etc/nginx/conf.d
#COPY nginx.conf /etc/nginx/
